site_name: Programming in AI Course
site_description: 'Материалы курса: программирование в ИИ'
site_url: ''
repo_url: ''
repo_name: ''

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - navigation.sections
    - toc.integrate

plugins:
  - search
  - mkdocs-jupyter
  # - mkdocs-jupyter:
      # execute: true
  # - awesome-pages

markdown_extensions:
  - admonition
  - toc:
      permalink: true
