site_name: Programming in AI Course
site_description: 'Материалы курса: программирование в ИИ'
site_url: ''
repo_url: ''
repo_name: ''

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - navigation.sections
    - toc.integrate

plugins:
  - search
  - mkdocs-jupyter
  # - mkdocs-jupyter:
      # execute: true

nav:
  - Главная: index.md
  - '2. NumPy и Pandas':
    - Обзор: 2_numpy_pandas/index.md
    - '2.1 NumPy: основы и векторизация': 2_numpy_pandas/numpy_basics.ipynb
    - '2.2 Линейная алгебра в NumPy': 2_numpy_pandas/numpy_linalg.ipynb
    - '2.3 Pandas: основы': 2_numpy_pandas/pandas_basics.ipynb
    - '2.4 Pandas: EDA и groupby': 2_numpy_pandas/pandas_eda_groupby.ipynb

markdown_extensions:
  - admonition
  - toc:
      permalink: true
